import { Link } from "react-router-dom";

const SECTIONS = [
  {
    id: "overview",
    title: "1. Who We Are",
    body: [
      "VENLAX Sports is operated by VENLAX LLC. We run a sports league platform at venlaxsports.com for Tennis, Pickleball, and Cricket leagues.",
      "Contact: support@venlaxsports.com",
    ],
  },
  {
    id: "data-collected",
    title: "2. Data We Collect",
    body: [
      "Account data: name, email address, city, gender (optional), and sport skill ratings you provide at sign-up or in your profile.",
      "Payment confirmation status (we never store card numbers — payments are processed by Stripe, Inc., a PCI-DSS Level 1 certified processor).",
      "Match history, scores, and standings generated by your participation in VENLAX leagues.",
      "Usage analytics: page views and feature interactions via PostHog. Session recording is only enabled if you explicitly consent (see Section 7).",
      "We do not collect location data, phone numbers, or social security numbers.",
    ],
  },
  {
    id: "how-used",
    title: "3. How We Use Your Data",
    body: [
      "To operate your account and process league registrations.",
      "To display standings, match schedules, and player profiles within the platform.",
      "To send transactional emails: registration confirmation, match reminders, score reports, and account notices. You cannot opt out of transactional emails while you have an active account.",
      "To improve the platform using aggregated, anonymized analytics.",
      "We do not use your data for advertising and do not sell or rent your personal data to any third party.",
    ],
  },
  {
    id: "sharing",
    title: "4. Data Sharing",
    body: [
      "Stripe, Inc. (stripe.com) — payment processing. Subject to Stripe's Privacy Policy.",
      "Google LLC — authentication via Google OAuth if you sign in with Google. Subject to Google's Privacy Policy.",
      "PostHog, Inc. — product analytics. Data is stored on US servers. Subject to PostHog's Privacy Policy.",
      "No other third parties receive your personal data.",
    ],
  },
  {
    id: "public",
    title: "5. Public Information",
    body: [
      "Your name, city, skill ratings, and league results are visible to other logged-in users on the platform.",
      "Your email address is never displayed publicly.",
      "If you want your profile to be less visible, contact support@venlaxsports.com.",
    ],
  },
  {
    id: "retention",
    title: "6. Data Retention",
    body: [
      "Account data is retained for as long as your account is active.",
      "To request deletion of your account and all associated personal data, email support@venlaxsports.com. We will process deletion requests within 30 days.",
      "Match records and standings may be anonymized and retained in aggregate form after account deletion.",
    ],
  },
  {
    id: "analytics-consent",
    title: "7. Analytics & Session Recording",
    body: [
      "We use PostHog for product analytics. Basic analytics (page views, feature clicks) are collected for all users to help us improve the platform.",
      "Session recording — which captures mouse movements and interactions — is disabled by default. We enable it only if you explicitly accept analytics via the consent banner.",
      "You can change your consent at any time by clearing your browser's localStorage for venlaxsports.com or contacting support@venlaxsports.com.",
    ],
  },
  {
    id: "rights",
    title: "8. Your Rights (CCPA / California Residents)",
    body: [
      "Right to know: You can request a copy of the personal information we hold about you.",
      "Right to delete: You can request deletion of your personal information.",
      "Right to opt out of sale: We do not sell personal information. No opt-out required.",
      "Right to non-discrimination: Exercising your privacy rights will not affect your access to VENLAX Sports services.",
      "To exercise these rights, email support@venlaxsports.com with the subject line 'Privacy Request'.",
    ],
  },
  {
    id: "security",
    title: "9. Security",
    body: [
      "All data is transmitted over TLS (HTTPS). Authentication tokens are stored in httpOnly cookies not accessible to JavaScript.",
      "Passwords are stored as bcrypt hashes. We never store plaintext passwords.",
      "While we take reasonable precautions, no internet transmission is 100% secure. We encourage you to use a strong, unique password.",
    ],
  },
  {
    id: "children",
    title: "10. Children's Privacy",
    body: [
      "VENLAX Sports is not intended for users under 13. We do not knowingly collect data from children under 13.",
      "If you believe a child under 13 has registered, contact support@venlaxsports.com and we will delete the account promptly.",
    ],
  },
  {
    id: "changes",
    title: "11. Changes to This Policy",
    body: [
      "We may update this Privacy Policy. Material changes will be communicated via email to registered users at least 7 days before taking effect.",
      "Continued use of the platform after changes take effect constitutes acceptance of the updated policy.",
    ],
  },
];

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      {/* Hero */}
      <div className="bg-gray-50 border-b border-gray-200 py-12 px-4">
        <div className="max-w-3xl mx-auto">
          <p className="text-xs font-semibold uppercase tracking-widest text-gray-500 mb-2">Legal</p>
          <h1 className="font-heading font-black text-4xl text-gray-900">Privacy Policy</h1>
          <p className="mt-3 text-gray-600">
            Last updated: May 2026. This policy explains what personal data VENLAX Sports collects,
            how it is used, and your rights under applicable privacy law including the CCPA.
          </p>
          <p className="mt-2 text-sm text-gray-500">
            Questions? Email{" "}
            <a href="mailto:support@venlaxsports.com" className="underline hover:text-gray-700">
              support@venlaxsports.com
            </a>
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 py-12 space-y-10">
        {SECTIONS.map((s) => (
          <section key={s.id} id={s.id}>
            <h2 className="font-heading font-bold text-xl text-gray-900 mb-4">{s.title}</h2>
            <ul className="space-y-3">
              {s.body.map((para, i) => (
                <li key={i} className="text-gray-700 text-sm leading-relaxed pl-4 border-l-2 border-gray-100">
                  {para}
                </li>
              ))}
            </ul>
          </section>
        ))}

        <div className="border-t border-gray-200 pt-8 text-sm text-gray-500 space-y-1">
          <p>VENLAX Sports is operated by VENLAX LLC.</p>
          <p>
            Payments processed by{" "}
            <a href="https://stripe.com" target="_blank" rel="noopener noreferrer" className="underline hover:text-gray-700">
              Stripe, Inc.
            </a>{" "}
            — PCI-DSS Level 1 certified.
          </p>
          <p className="mt-4">
            <Link to="/terms" className="underline hover:text-gray-700">Terms of Service</Link>
            {" · "}
            <Link to="/" className="underline hover:text-gray-700">← Back to home</Link>
          </p>
        </div>
      </div>
    </div>
  );
}
